// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (db pull / db push / migrate) talk to Postgres directly,
    // bypassing the pgbouncer pooler used by the running app.
    url: process.env["DIRECT_URL"],
  },
});
